terraform {
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.1"
    }
  }
}

resource "local_file" "info" {
  content  = "This is a placeholder file generated by Terraform for the auto-sorpresa de cumpleaños application. In a real-world scenario, this file would define cloud infrastructure resources (e.g., VMs, databases, load balancers) for deploying the application."
  filename = "${path.module}/terraform_info.txt"
}

output "info_file_path" {
  value = local_file.info.filename
  description = "Path to the informational file created by Terraform."
}
